In [ ]:
# First Lession

In [1]:
import numpy as np

print(np.__version__)

2.2.2


In [2]:
my_list = [1, 2, 4, 5]

my_list = my_list * 2

print(my_list)

[1, 2, 4, 5, 1, 2, 4, 5]


In [4]:
array = np.array([1, 2, 4, 5, 6])
print(array)
print(type(array))

[1 2 4 5 6]
<class 'numpy.ndarray'>


In [ ]:
# Second Lesson

In [28]:
array = np.array([[['a','b', 'd'], ['e','d', 'd'],['a','b', 'd']],
                  [['h','b', 'd'], ['a','b', 'M'],['a','s', 'd']],
                  [['a','b', 'l'], ['a','f', 'd'],['.','b','l']]])

# print(array.shape)
print(array[1,1,2]+array[1,1,0]+array[2,0,2]+array[2,0,2]+array[0,1,0]+array[1,2,1]+array[1,0,0]+array[2,2,0])

Mallesh.


In [ ]:
#lession 3 - 2D array

In [50]:
array = np.array([[1,2,3,4],
                  [3,4,3,4],
                  [1,2,3,4],
                  [1,2,3,4]])
# print(array.ndim)

# print(array[:, 3])

print(array.dtype)

int64


In [62]:
ones = np.zeros((4, 2, 2)) # A 3x3 matrix of ones
print(ones.ndim)

3


In [63]:
range_array = np.arange(0, 10, 2) # Start, stop (exclusive), step
print("\nRange array:", range_array) # [0 2 4 6 8]


Range array: [0 2 4 6 8]


In [68]:
random_array = np.random.rand(2, 3) # A 2x3 matrix of random floats
print("\nRandom array:\n", random_array)


Random array:
 [[0.91995655 0.7418136  0.45034317]
 [0.05341055 0.9370916  0.69101572]]


In [71]:
linspace_array = np.linspace(0, 10, 5) # 5 points from 0 to 10 (inclusive)
print("\nLinspace array:", linspace_array)


Linspace array: [ 0.   2.5  5.   7.5 10. ]


In [ ]:
#Arithematic 

In [75]:
array = np.array([1,2,3])

print(array+1)
print(array-1)
print(array*1)
print(array/1)
print(array**1)

[2 3 4]
[0 1 2]
[1 2 3]
[1. 2. 3.]
[1 2 3]


In [ ]:
#Vectorize math functions

In [80]:
array = np.array([12,2.3,32,4.322,2,6])

print(np.sqrt(array))
print(np.round(array))
print(np.pi)

[3.46410162 1.51657509 5.65685425 2.07894204 1.41421356 2.44948974]
[12.  2. 32.  4.  2.  6.]
3.141592653589793


In [83]:
radi = np.array([1,2,3])

print(np.pi * radi ** 2)

[ 3.14159265 12.56637061 28.27433388]


In [82]:
#Element-wise arithematic